version: "2"
services:
   fhem:
       expose:
               - "8083"
               - "7072"
       ports:
               - "8083:8083"
               - "7072:7072"
       build: fhem
       privileged: true
       devices:
               - "/dev/ttyUSB0:/dev/ttyUSB0"
       volumes:
               - ./fhem/start.sh:/opt/fhem/start.sh
               - ./fhem/log/:/opt/fhem/log
               - ./fhem/backup/:/opt/fhem/backup
               - ./fhem/data/fhem.cfg:/opt/fhem/fhem.cfg
               - ./fhem/data/FHEM/controls.txt:/opt/fhem/FHEM/controls.txt
               - ./fhem/data/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
               - ./fhem/data/contrib/dblog/db.conf:/opt/fhem/contrib/dblog/db.conf

       depends_on:
               - "mysql"

   mysql:
       expose:
               - "3306"
               - "33060"
       ports:
               - "3306:3306"
               - "33060:33060"
       image: mysql/mysql-server:latest
       volumes:
               - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
               - ./mysql/data:/var/lib/mysql
       environment:
               - MYSQL_RANDOM_ROOT_PASSWORD=yes

